### ISSUE TITLE
Possible infinite loop in the test in the master branch

### ISSUE THREAD

**Issue by LarinK65** [learning-process/ppc-2024-threads#466]
https://github.com/learning-process/ppc-2024-threads/blob/91f2ccabbef9996b223eceb57ead9a4d03f06329/tasks/omp/dostavalov_s_sop_gradient/src/ops_omp.cpp#L93-L142

The code can be executed indefinitely or for a very long time due to the fact that the matrix consists of random numbers and as a result of errors in rounding floating-point numbers.

Code added in #284.

**Comment by allnes** [comment]
@LarinK65 this work was removed here - https://github.com/learning-process/ppc-2024-threads/pull/536
